### ISSUE TITLE
Composer is not cancelled 

### ISSUE THREAD

**Issue by wiktorwar** [MasayukiSuda/Mp4Composer-android#55]
Hey,
Thank you for writing this library, it's super helpful.
I use version `v0.3.4` and I've noticed that after calling `composer.cancel()` listener is still emitting progress values in `onProgress()` until I keep the app alive.
It may be that I call `cancel` on different thread that `composer` is operating, does it matter?

**Comment by kachi1227** [comment]
+1 to this issue.  It seems like cancel only works sporadically since it just calls `ExecutorService.shutdownNow()` whose documentation says 

> There are no guarantees beyond best-effort attempts to stop processing actively executing tasks.  For example, typical implementations will cancel via {@link Thread#interrupt}, so any task that fails to respond to interrupts may never terminate.

I think more straightforward and effective way of cancelling would be to create a `canceled` boolean inside Mp4ComposerEngine that would prematurely exit the loops inside `runPipelines()` and `runPipelinesNoAudio()` when it was set to true via `Mp4Composer.cancel()`. If you think this approach would work, given your understanding of the library, let me know and I can go ahead and create a PR for this.
